#+TITLE: Wacuri frontend

https://github.com/alexiscott/wacuri

1. Setup the backend over https://github.com/alexiscott/wacuri-api - This process basically involves creating a broker and having it available on a public URL.

2. Now add the path to the broker's public URL in this repo in App.js

* Setup for a Mac and a real iphone.
Run initial tasks
#+begin_src shell
npm install
cd ios
pod install
#+end_src

3. Open the workspace file  in ~Xcode~ code~basicwebrtcexample.xcworkspace . You will need to have configured ~Xcode~ to work with the frontend app, to work with your App and to open in an iphon. SEE LINK. Now, Build the APP via xCode.


4. Trust the app on the iphone Settings/General/Profiles and device management/ 
- Open the app. You might get a message about them not being on the same network. I unplugged the USB socket and then the app opened with the camera on.

  ---
  I then opened an emulator on my Linux Box ( You will need to have setup Android Studio).

-  set the public URL.
- npm start
  - npm run android
    - You should see the connections number on the Android page increase.
